# Waypoints configuration for drone-control-start
# 说明:
#   该文件定义仿真 / 真实环境中无人机可能用到的一系列命名航点。
#   顶层流程 (mission orchestrator) 可以读取此文件，根据名称检索坐标。
#
# 坐标系假设:
#   - 使用与仿真一致的全局水平坐标系 (例如 map / world)
#   - 单位: 米
#   - yaw 以度为单位 (右手系, 绕Z轴, 0度朝X正方向, 正向逆时针)
#
# 命名规则建议:
#   pointX               通用关键点
#   shelf1_rowY_colZ     货架1 (row行, col列), 行从顶向下或自上而下请与注释保持一致
#   shelf1_top_colZ      货架1 顶部列点
#   shelf2_...           货架2 同理
#   charge               充电点
#
# 货架行列说明 (示例):
#   这里给出假设，需根据你仿真中真实摆放位置修改:
#   - 货架面向 +Y 方向
#   - 行 row1 = 第一层(最上层), row2 = 第二层, row3 = 第三层(地面), top = 顶面悬停检测点
#   - 列 col1 从左到右 (观察面向货架正面时)
#
# 可根据需要继续拓展更多逻辑点，如：
#   - 识别准备点 (approach)
#   - QR 对准点 (qr_align)
#   - 降落缓冲点 (pre_land)
#
# 修改后请重新加载或在节点中监听文件变化(如果实现了热加载)。
#
# 顶层/中间层读取方式示例 (Python):
#   import yaml
#   data = yaml.safe_load(open('waypoints.yaml'))
#   wp = data['shelf1']['row1']['col1']  # => {x: ..., y: ..., z: ..., yaw: ...}
#
# 注意: 以下坐标为占位示例，你需要根据实际场景更新。

# 通用关键点
points:
  point1:
    x: 3.5
    y: 3.2
    z: 0.5
    yaw: 0.0
  point2:
    x: 6.0
    y: 1.4
    z: 1.0
    yaw: 0.0

# 充电站
charge:
  x: 8.0
  y: 2.3
  z: 0.3         # 悬停高度 (若需要降落, 流程里再逐步降到地面)
  yaw: 180.0

# 货架1 定义
shelf1:
  # 顶部 (top) 四列点 (用于从上方巡检或对齐)
  top:
    col1: { x: 2.75,  y: 4,  z: 2.3,  yaw: 0.0 }
    col2: { x: 4.25,  y: 4,  z: 2.3,  yaw: 0.0 }
    col3: { x: 5.5,  y: 4,  z: 2.3,  yaw: 0.0 }
    col4: { x: 6.5,  y: 4,  z: 2.3,  yaw: 0.0 }

  # 第一行 (row1) - 上层
  row1:
    col1: { x: 2.75,  y: 2.8,  z: 1.7,  yaw: 0.0 }
    col2: { x: 4.25,  y: 2.8,  z: 1.7,  yaw: 0.0 }
    col3: { x: 5.5,  y: 2.8,  z: 1.7,  yaw: 0.0 }
    col4: { x: 6.5,  y: 2.8,  z: 1.7,  yaw: 0.0 }

  # 第二行 (row2) - 中层
  row2:
    col1: { x: 2.75,  y: 2.8,  z: 1.0,  yaw: 0.0 }
    col2: { x: 4.25,  y: 2.8,  z: 1.0,  yaw: 0.0 }
    col3: { x: 5.5,  y: 2.8,  z: 1.0,  yaw: 0.0 }
    col4: { x: 6.5,  y: 2.8,  z: 1.0,  yaw: 0.0 }

  # 第三行 (row3) - 地面层
  row3:
    col1: { x: 2.75,  y: 2.8,  z: 0.3,  yaw: 0.0 }
    col2: { x: 4.25,  y: 2.8,  z: 0.3,  yaw: 0.0 }
    col3: { x: 5.5,  y: 2.8,  z: 0.3,  yaw: 0.0 }
    col4: { x: 6.5,  y: 2.8,  z: 0.3,  yaw: 0.0 }

# 货架2 定义 (复制 shelf1, 可按真实位置整体偏移或重新标定)
shelf2:
  top:
    col1: { x: 2.75,  y: 0.6,  z: 2.3,  yaw: 0.0 }
    col2: { x: 4.25,  y: 0.6,  z: 2.3,  yaw: 0.0 }
    col3: { x: 5.5,  y: 0.6,  z: 2.3,  yaw: 0.0 }
    col4: { x: 6.5,  y: 0.6,  z: 2.3,  yaw: 0.0 }
  row1:
    col1: { x: 2.75,  y: 1.8,  z: 1.7,  yaw: 0.0 }
    col2: { x: 4.25,  y: 1.8,  z: 1.7,  yaw: 0.0 }
    col3: { x: 5.5,  y: 1.8,  z: 1.7,  yaw: 0.0 }
    col4: { x: 6.5,  y: 1.8,  z: 1.7,  yaw: 0.0 }
  row2:
    col1: { x: 2.75,  y: 1.8,  z: 1.0,  yaw: 0.0 }
    col2: { x: 4.25,  y: 1.8,  z: 1.0,  yaw: 0.0 }
    col3: { x: 5.5,  y: 1.8,  z: 1.0,  yaw: 0.0 }
    col4: { x: 6.5,  y: 1.8,  z: 1.0,  yaw: 0.0 }
  row3:
    col1: { x: 2.75,  y: 1.8,  z: 0.3,  yaw: 0.0 }
    col2: { x: 4.25,  y: 1.8,  z: 0.3,  yaw: 0.0 }
    col3: { x: 5.5,  y: 1.8,  z: 0.3,  yaw: 0.0 }
    col4: { x: 6.5,  y: 1.8,  z: 0.3,  yaw: 0.0 }
